// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjq7cMi6_3ulaSWsIluIvNVvv5HCff4cY',
    appId: '1:661711729412:web:14aa486fdbdfe0d95ad651',
    messagingSenderId: '661711729412',
    projectId: 'labssadz-67b38',
    authDomain: 'labssadz-67b38.firebaseapp.com',
    storageBucket: 'labssadz-67b38.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpxPF0XBQfkqx3gkWSKKYVeyLTX8QwS9w',
    appId: '1:661711729412:android:21a2a2e90dd751b15ad651',
    messagingSenderId: '661711729412',
    projectId: 'labssadz-67b38',
    storageBucket: 'labssadz-67b38.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQco7U7LhOoRA-4GmLLdaa0gCPdCPwIks',
    appId: '1:661711729412:ios:1c619bbb682debf05ad651',
    messagingSenderId: '661711729412',
    projectId: 'labssadz-67b38',
    storageBucket: 'labssadz-67b38.firebasestorage.app',
    iosBundleId: 'com.example.labsadz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQco7U7LhOoRA-4GmLLdaa0gCPdCPwIks',
    appId: '1:661711729412:ios:1c619bbb682debf05ad651',
    messagingSenderId: '661711729412',
    projectId: 'labssadz-67b38',
    storageBucket: 'labssadz-67b38.firebasestorage.app',
    iosBundleId: 'com.example.labsadz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjq7cMi6_3ulaSWsIluIvNVvv5HCff4cY',
    appId: '1:661711729412:web:6019e10a790c6bc25ad651',
    messagingSenderId: '661711729412',
    projectId: 'labssadz-67b38',
    authDomain: 'labssadz-67b38.firebaseapp.com',
    storageBucket: 'labssadz-67b38.firebasestorage.app',
  );
}
